version: '3.8'

services:
  reactivation-system:
    build:
      context: .
      dockerfile: Dockerfile.reactivation
    container_name: fullforce-reativacao
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - PORT=4002
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_ACCESS_TOKEN=${GOOGLE_ACCESS_TOKEN}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - WAHA_API_URL=${WAHA_API_URL}
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_SESSION=${WAHA_SESSION:-fullforce-session}
      - AUTO_CAMPAIGN=${AUTO_CAMPAIGN:-false}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4002/api/test', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
    networks:
      - fullforce-network

networks:
  fullforce-network:
    driver: bridge
