# Configuração de Build para o Netlify
# Otimizado para um projeto em subdiretório (monorepo-like)
[build]
  # Define o diretório base onde o build será executado
  base    = "fullforce-site"
  # Comando para instalar dependências (usando 'ci' para builds mais rápidos e consistentes) e buildar o projeto
  command = "npm ci && npm run build"
  # Diretório de publicação (relativo ao 'base')
  publish = "dist"

# Variáveis de ambiente para garantir consistência no build
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION  = "10"

# Regra de redirecionamento para Single Page Applications (SPA)
# Garante que todas as rotas sejam direcionadas para o index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# Configurações de Headers para Performance e Segurança
[[headers]]
  for = "/*"
  [headers.values]
    # Headers de Segurança recomendados
    X-Frame-Options           = "DENY"
    X-XSS-Protection          = "1; mode=block"
    X-Content-Type-Options    = "nosniff"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "geolocation=(), microphone=(), camera=()"

# Headers de Cache para assets imutáveis (com hash no nome)
# Vite coloca os assets buildados em /assets/
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"